# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a45460dd77504dcdeb22f3ad60555f951fead450331a6612573025efaba93b74ff40093ec7c9fe0fc15a836a5b25dd10188090114c6cf5faf2925dc36aebf38d

test:
  secret_key_base: 367002992eb465d6b466fdd3287d27d0bc749e0c50f37a731b8705c5b0d69584e9e61d188583ecb7ac0efa2552b9e0fee0d12a35900f109608ff2155708314b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
